# 通用签名地址：http://127.0.0.1:8080/sign?key=114514、这只是一个例子，请根据你个人的地址进行填写
# 如果账号格式中配置了签名地址，则会优先使用该签名地址，如果未配置则会使用 sign_api_addr 的地址。
sign_api_addr: http://127.0.0.1:8080/sign?key=114514

# 过滤自身消息：开启(1)、关闭(0)
# 本插件只支持1、2、6，其他协议不再进行适配
# 登录平台：1:安卓手机、2:安卓平板、3:安卓手表、4:MacOS、5:iPad、6:Tim3.5.1
# 登录平台目前签名(qsign)仅支持安卓手机、安卓平板、Tim(不推荐使用)

# 账号格式：过滤自身消息-登录平台-QQ账号-QQ密码-签名地址(可选)
# 以下是一点例子，可手动配置~
# account:
#   - 1:2:1234567890:abc123
#   - 1:2:0987654321:abc123:http://127.0.0.1:8080/sign?key=114514

# 启用账号
account:

# 禁用账号
# 跟上方一模一样的配置，无非就是位置不一样，暂时保存罢了。
disable:
